#!/bin/bash
source /etc/docker/moxie.sh

docker run --rm -it \
    --privileged=true \
    -v /run/docker.sock:/run/docker.sock \
    -v /srv/lucifer.pault.ag/prod/moxie:/moxie \
    -e DATABASE_URL=${DATABASE_URL} \
    paultag/moxie \
    bash
