"""Cron-ify job scheduling

Revision ID: 344e26c7948
Revises: 389e540c827
Create Date: 2015-08-13 16:13:00.559773

"""

# revision identifiers, used by Alembic.
revision = '344e26c7948'
down_revision = '389e540c827'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('crontab', sa.Text(), nullable=True))
    op.add_column('job', sa.Column('timezone', sa.Text(), nullable=True))
    op.drop_column('job', 'interval')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('interval', postgresql.INTERVAL(), autoincrement=False, nullable=True))
    op.drop_column('job', 'timezone')
    op.drop_column('job', 'crontab')
    ### end Alembic commands ###
