---
maintainers:
    - name: "Paul Tagliamonte"
      email: "paultag@example.com"

jobs:
    - name: "crank-hy"
      description: "Crank (Hylang)"
      maintainer: "paultag@example.com"
      interval: 10
      # interval: 30
      command: "/opt/pault.ag/crank/eg/hy.hy"
      image: "paultag/crank"
      volumes: "crank"

volume-sets:
    - name: "crank"
      values:
        - host: "/srv/leliel.pault.ag/dev/crank/"
          container: "/crank/"
